# Project Name = Aixt project, https =//gitlab.com/fermarsan/aixt-project.git
# File Name = Explorer16-PIC24.toml
# Author = Fernando Martínez Santa
# Date = 2024
# License = MIT
#
# Description = This is the setup file for the Explorer16 (with PIC24)
#               port of Aixt project
port =    "ESP8266-NodeMCU-v3"
device =  "ESP8266"
board =   "ESP8266 NodeMCU v3"
backend = "arduino"

cc_linux =   "xc16"
cc_windows = "C:\Program Files (x86)\Arduino.exe"
cc_flags =   "-o"

path = "ports/Espressif/ESP8266-NodeMCU-v3"

api_modules = [
    "machine",
    "time"
]

fixed_size_arrays =  "true"
fixed_size_strings = "true"

void =  ""
bool =  "bool"

i8 =    "int8_t"
i16 =   "int16_t"
int =   "int32_t"
i64 =   "int64_t"
isize = "int32_t"
int_literal = "int32_t"

u8 =    "uint8_t"
u16 =   "uint16_t"
u32 =   "uint32_t"
u64 =   "unit64_t"
usize = "uint32_t"

f32 = "float"
f64 = "=== NOT SUPPORTED ==="
float_literal = "float"

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="

main_ret_type = "int"
main_params =   "void "

api_module = [

    "port"
    "pin"
    "pwm"
    "time"
    "uart"
    "adc"
]
#headers = [
#    "xc.h",
#    "stdint.h",
#    "stdbool.h",
#]

#macros = [
#    "FCY 8000000UL"
#]

#config_operator = "#pragma config"

#configuration = [
#    "POSCMOD = XT",
#    "OSCIOFNC = ON",
#    "FCKSM = CSDCMD",
#    "FNOSC = PRI",
#    "IESO = ON",
#    "WDTPS = PS32768",
#    "FWPSA = PR128",
#    "WINDIS = ON",
#    "FWDTEN = OFF",
#    "ICS = PGx2",
#    "GWRP = OFF",
#    "GCP = OFF",
#    \\"JTAGEN = OFF"
#]

#initialization = [
#   "AD1PCFG = 0xFFDF;      // Analog inputs for Explorer16 POT and TSENS",
#   "AD1CSSL = 0;           // no scanning required",
#   "AD1CON2 = 0;           // use MUXA, AVss and AVdd are used as Vref+/-",
#   "AD1CON3 = 0x1F02;      // Tsamp = 32 x Tad; Tad=125ns",
#   "AD1CON1bits.ADON = 1;  // turn on the ADC",
#    "TRISA = 0xff00;        // select the PORTA pins as outputs to drive the LEDs",
#]

[aliases ]