# Project Name = Aixt project, https =//gitlab.com/fermarsan/aixt-project.git
# File Name = Explorer16-PIC24.toml
# Author = Fernando Martínez Santa
# Date = 2024
# License = MIT
#
# Description = This is the setup file for the Explorer16 (with PIC24)
#               port of Aixt project
port =    "ESP8266-NodeMCU-v3"
device =  "ESP8266"
board =   "ESP8266 NodeMCU v3"
backend = "arduino"

cc_linux =   
cc_windows = "C:\\Program Files (x86)\\Arduino.exe"
cc_flags =   "-o"
#C:\Users\User\repos\aixt-ESPE3286\ports\Espressif\ESP8266-NodeMCU-v3
path = "Espressif/ESP8266-NodeMCU-v3"


api_modules = [
    "machine",
    "time"
]

fixed_size_arrays =  "true"
fixed_size_strings = "true"

void =  ""
bool =  "bool"

i8 =    "int8_t"
i16 =   "int16_t"
int =   "int32_t"
i64 =   "int64_t"
isize = "int32_t"
int_literal = "int32_t"

u8 =    "uint8_t"
u16 =   "uint16_t"
u32 =   "uint32_t"
u64 =   "unit64_t"
usize = "uint32_t"

f32 = "float"
f64 = "=== NOT SUPPORTED ==="
float_literal = "float"

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="

main_ret_type = "int"
main_params =   "void "

api_module = [

    "port"
    "pin"
    "pwm"
    "time"
    "uart"
    "adc"
]


[aliases ]